#pragma once

#include <cstddef>

namespace RitualHelper {

struct UniqueCatalogEntry { const char* category; const char* name; const char* baseType; };

inline constexpr UniqueCatalogEntry kUniqueCatalog[] = {
    {"unique weapon", "The Dancing Dervish", "Scimitar"},
    {"unique weapon", "Runeseeker's Call", "Runic Fork"},
    {"unique weapon", "Winter's Bite", "Glass Shank"},
    {"unique weapon", "Bluetongue", "Shortsword"},
    {"unique weapon", "Redbeak", "Shortsword"},
    {"unique weapon", "The Ordained", "Grand Spear"},
    {"unique weapon", "Guiding Palm of the Eye", "Shrine Sceptre"},
    {"unique weapon", "Guiding Palm of the Heart", "Shrine Sceptre"},
    {"unique weapon", "Guiding Palm of the Mind", "Shrine Sceptre"},
    {"unique weapon", "Sacred Flame", "Shrine Sceptre"},
    {"unique weapon", "Adonia's Ego", "Siphoning Wand"},
    {"unique weapon", "Sylvan's Effigy", "Stoic Sceptre"},
    {"unique weapon", "Twisted Empyrean", "Aberrant Sledge"},
    {"unique weapon", "Periphery", "Heartwood Shortbow"},
    {"unique weapon", "Mjölner", "Torment Club"},
    {"unique weapon", "Liminal Coil", "Twisted Wand"},
    {"unique weapon", "Brutus' Lead Sprinkler", "Morning Star"},
    {"unique weapon", "Fury of the King", "Ashbark Talisman"},
    {"unique weapon", "Spire of Ire", "Helix Spear"},
    {"unique weapon", "Skysliver", "Winged Spear"},
    {"unique weapon", "Redemption", "Trarthan Cannon"},
    {"unique weapon", "The Whispering Ice", "Permafrost Staff"},
    {"unique weapon", "Atziri's Rule", "Reflecting Staff"},
    {"unique weapon", "The Hammer of Faith", "Giant Maul"},
    {"unique weapon", "Saitha's Spear", "Barbed Spear"},
    {"unique weapon", "Trenchtimbre", "Spiked Club"},
    {"unique weapon", "Quill Rain", "Shortbow"},
    {"unique weapon", "Marohi Erqi", "Totemic Greatclub"},
    {"unique weapon", "Duality", "Warding Quarterstaff"},
    {"unique weapon", "Doomfletch", "Composite Bow"},
    {"unique weapon", "Voltaxic Rift", "Fanatic Bow"},
    {"unique weapon", "Atziri's Contempt", "Pronged Spear"},
    {"unique weapon", "Quecholli", "Crumbling Maul"},
    {"unique weapon", "Enezun's Charge", "Volatile Wand"},
    {"unique weapon", "Collapsing Horizon", "Wyrm Quarterstaff"},
    {"unique weapon", "Lioneye's Glare", "Heavy Bow"},
    {"unique weapon", "The Raven's Flock", "Perching Staff"},
    {"unique weapon", "Nebuloch", "Execratus Hammer"},
    {"unique weapon", "Cursecarver", "Acrid Wand"},
    {"unique weapon", "Frostbreath", "Slim Mace"},
    {"unique weapon", "Chainsting", "Hunting Spear"},
    {"unique weapon", "Tangletongue", "Forked Spear"},
    {"unique weapon", "The Dark Defiler", "Rattling Sceptre"},
    {"unique weapon", "Lifesprig", "Attuned Wand"},
    {"unique weapon", "Widowhail", "Crude Bow"},
    {"unique weapon", "Rampart Raptor", "Tense Crossbow"},
    {"unique weapon", "Double Vision", "Dyad Crossbow"},
    {"unique weapon", "The Last Lament", "Desolate Crossbow"},
    {"unique weapon", "Pillar of the Caged God", "Long Quarterstaff"},
    {"unique weapon", "The Sentry", "Gothic Quarterstaff"},
    {"unique weapon", "Matsya", "Crescent Quarterstaff"},
    {"unique weapon", "Nazir's Judgement", "Steelpoint Quarterstaff"},
    {"unique weapon", "Earthbound", "Voltaic Staff"},
    {"unique weapon", "The Empty Roar", "Cultist Greathammer"},
    {"unique weapon", "Shyaba", "Temple Maul"},
    {"unique weapon", "Chober Chaber", "Leaden Greathammer"},
    {"unique weapon", "Olrovasara", "Torment Club"},
    {"unique weapon", "Sadist's Mercy", "Flanged Mace"},
    {"unique weapon", "Tyranny's Grip", "Ironhead Spear"},
    {"unique weapon", "Daevata's Wind", "War Spear"},
    {"unique weapon", "Font of Power", "Omen Sceptre"},
    {"unique weapon", "Sanguine Diviner", "Bone Wand"},
    {"unique weapon", "Death's Harp", "Dualstring Bow"},
    {"unique weapon", "Slivertongue", "Zealot Bow"},
    {"unique weapon", "Mist Whisper", "Makeshift Crossbow"},
    {"unique weapon", "Taryn's Shiver", "Gelid Staff"},
    {"unique weapon", "The Burden of Shadows", "Chiming Staff"},
    {"unique weapon", "Sire of Shards", "Chiming Staff"},
    {"unique weapon", "Hrimnor's Hymn", "Oak Greathammer"},
    {"unique weapon", "Trephina", "Forge Maul"},
    {"unique weapon", "Brain Rattler", "Studded Greatclub"},
    {"unique weapon", "Brynhand's Mark", "Wooden Club"},
    {"unique weapon", "Sculpted Suffering", "Warpick"},
    {"unique weapon", "Seeing Stars", "Plated Mace"},
    {"unique weapon", "Splinter of Lorrata", "Hardwood Spear"},
    {"unique weapon", "The Wicked Quill", "Withered Wand"},
    {"unique weapon", "Ironbound", "Warden Bow"},
    {"unique weapon", "Splinterheart", "Recurve Bow"},
    {"unique weapon", "The Blood Thorn", "Wrapped Quarterstaff"},
    {"unique weapon", "Dusk Vigil", "Ashen Staff"},
    {"unique weapon", "The Searing Touch", "Pyrophyte Staff"},
    {"unique weapon", "Hoghunt", "Felled Greatclub"},
    {"unique weapon", "Tidebreaker", "Pointed Maul"},
    {"unique weapon", "Fairgraves' Curse", "Artillery Bow"},
    {"unique weapon", "The Unborn Lich", "Ravenous Staff"},
    {"unique weapon", "Amor Mandragora", "Changeling Talisman"},
    {"unique weapon", "Surge of the Tide", "Lumbering Talisman"},
    {"unique weapon", "Spiteful Floret", "Nettle Talisman"},
    {"unique weapon", "Hysseg's Claw", "Familial Talisman"},
    {"unique weapon", "The Flesh Poppet", "Vicious Talisman"},
    {"unique weapon", "Serle's Grit", "Kalguuran Forgehammer"},
    {"unique armour", "Temporalis", "Silk Robe"},
    {"unique armour", "Rathpith Globe", "Sacred Focus"},
    {"unique armour", "Death Articulated", "Ornate Gauntlets"},
    {"unique armour", "Hateforge", "Moulded Mitts"},
    {"unique armour", "Sandstorm Visage", "Chain Tiara"},
    {"unique armour", "Tabula Rasa", "Garment"},
    {"unique armour", "Morior Invictus", "Grand Regalia"},
    {"unique armour", "Cadiro's Gambit", "Primed Quiver"},
    {"unique armour", "Skin of the Loyal", "Garment"},
    {"unique armour", "Sine Aequo", "Grand Manchettes"},
    {"unique armour", "Alpha's Howl", "Armoured Cap"},
    {"unique armour", "Hand of Wisdom and Action", "Furtive Wraps"},
    {"unique armour", "Maligaro's Virtuosity", "Fine Bracers"},
    {"unique armour", "Loreweave", "Ornate Ringmail"},
    {"unique armour", "Svalinn", "Crucible Tower Shield"},
    {"unique armour", "Sunsplinter", "Array Buckler"},
    {"unique armour", "The Vertex", "Tribal Mask"},
    {"unique armour", "The Brass Dome", "Champion Cuirass"},
    {"unique armour", "Nightfall", "Glacial Fortress"},
    {"unique armour", "Atziri's Splendour", "Sacrificial Regalia"},
    {"unique armour", "Decree of Flight", "Ancient Leggings"},
    {"unique armour", "Glimpse of Chaos", "Tribal Mask"},
    {"unique armour", "The Bringer of Rain", "Decorated Helm"},
    {"unique armour", "Hyrri's Ire", "Armoured Vest"},
    {"unique armour", "The Covenant", "Altar Robe"},
    {"unique armour", "Kaom's Heart", "Conqueror Plate"},
    {"unique armour", "Pragmatism", "Explorer Armour"},
    {"unique armour", "The Master's Reach", "Tethering Bands"},
    {"unique armour", "Cornathaum", "Heavy Crown"},
    {"unique armour", "Forgotten Warden", "Primal Markings"},
    {"unique armour", "Crown of the Victor", "Iron Crown"},
    {"unique armour", "Bones of Ullr", "Lattice Sandals"},
    {"unique armour", "Thrillsteel", "Spired Greathelm"},
    {"unique armour", "Ab Aeterno", "Grand Cuisses"},
    {"unique armour", "Prism Guardian", "Intricate Crest Shield"},
    {"unique armour", "Goldrim", "Felt Cap"},
    {"unique armour", "Greymake", "Brimmed Helm"},
    {"unique armour", "Essentia Sanguis", "Furtive Wraps"},
    {"unique armour", "Leopold's Applause", "Embroidered Gloves"},
    {"unique armour", "Facebreaker", "Stocky Mitts"},
    {"unique armour", "Asphyxia's Wrath", "Broadhead Quiver"},
    {"unique armour", "Chernobog's Pillar", "Blacksteel Tower Shield"},
    {"unique armour", "Queen of the Forest", "Smuggler Coat"},
    {"unique armour", "Blackbraid", "Fur Plate"},
    {"unique armour", "Cloak of Defiance", "Havoc Raiment"},
    {"unique armour", "Mahuxotl's Machination", "Omen Crest Shield"},
    {"unique armour", "Horror's Flight", "Engraved Bracers"},
    {"unique armour", "Sands of Silk", "Shrouded Vest"},
    {"unique armour", "Cloak of Flame", "Silk Robe"},
    {"unique armour", "Windscream", "Feathered Sandals"},
    {"unique armour", "Myris Uxor", "Covert Hood"},
    {"unique armour", "Constricting Command", "Viper Cap"},
    {"unique armour", "Mind of the Council", "Death Mask"},
    {"unique armour", "Thunderfist", "Utility Wraps"},
    {"unique armour", "Zerphi's Serape", "Scalper's Jacket"},
    {"unique armour", "Enfolding Dawn", "Pilgrim Vestments"},
    {"unique armour", "Atziri's Step", "Cinched Boots"},
    {"unique armour", "Gravebind", "Rope Cuffs"},
    {"unique armour", "Silks of Veneration", "Enlightened Robe"},
    {"unique armour", "Painter's Servant", "Torn Gloves"},
    {"unique armour", "Solus Ipse", "Grand Visage"},
    {"unique armour", "Redblade Banner", "Heraldric Tower Shield"},
    {"unique armour", "Indigon", "Magus Tiara"},
    {"unique armour", "The Coming Calamity", "Heroic Armour"},
    {"unique armour", "Crown of Eyes", "Vermeil Circlet"},
    {"unique armour", "Bristleboar", "Leather Vest"},
    {"unique armour", "Foxshade", "Quilted Vest"},
    {"unique armour", "Ashrend", "Pathfinder Coat"},
    {"unique armour", "Briskwrap", "Rhoahide Coat"},
    {"unique armour", "Dustbloom", "Studded Vest"},
    {"unique armour", "The Rat Cage", "Scout's Vest"},
    {"unique armour", "Quatl's Molt", "Serpentscale Coat"},
    {"unique armour", "Apron of Emiran", "Hermit Garb"},
    {"unique armour", "Gloomform", "Waxed Jacket"},
    {"unique armour", "Sierran Inheritance", "Marabout Garb"},
    {"unique armour", "The Dancing Mirage", "Wayfarer Jacket"},
    {"unique armour", "Redflare Conduit", "Anchorite Garb"},
    {"unique armour", "Ghostwrithe", "Tattered Robe"},
    {"unique armour", "Bitterbloom", "Feathered Robe"},
    {"unique armour", "The Black Doubt", "Hexer's Robe"},
    {"unique armour", "Necromantle", "Bone Raiment"},
    {"unique armour", "Prayers for Rain", "Keth Raiment"},
    {"unique armour", "Tetzlapokal's Desire", "Votive Raiment"},
    {"unique armour", "Bramblejack", "Rusted Cuirass"},
    {"unique armour", "Edyrn's Tusks", "Iron Cuirass"},
    {"unique armour", "Titanrot Cataphract", "Maraketh Cuirass"},
    {"unique armour", "Wandering Reliquary", "Steel Plate"},
    {"unique armour", "Kingsguard", "Full Plate"},
    {"unique armour", "Greed's Embrace", "Vaal Cuirass"},
    {"unique armour", "Coat of Red", "Chain Mail"},
    {"unique armour", "The Barrow Dweller", "Rogue Armour"},
    {"unique armour", "Irongrasp", "Vagabond Armour"},
    {"unique armour", "Pariah's Embrace", "Cloaked Mail"},
    {"unique armour", "Belly of the Beast", "Explorer Armour"},
    {"unique armour", "Doryani's Prototype", "Scale Mail"},
    {"unique armour", "Perfidy", "Knight Armour"},
    {"unique armour", "Widow's Reign", "Knight Armour"},
    {"unique armour", "The Sunken Vessel", "Knight Armour"},
    {"unique armour", "Icetomb", "Mail Vestments"},
    {"unique armour", "Reverie", "Shaman Mantle"},
    {"unique armour", "Voll's Protector", "Ironclad Vestments"},
    {"unique armour", "Soul Mantle", "Sacrificial Mantle"},
    {"unique armour", "Couture of Crimson", "Gilded Vestments"},
    {"unique armour", "Briarpatch", "Laced Boots"},
    {"unique armour", "Gamblesprint", "Embossed Boots"},
    {"unique armour", "Bushwhack", "Lizardscale Boots"},
    {"unique armour", "Ghostmarch", "Threaded Shoes"},
    {"unique armour", "Luminous Pace", "Straw Sandals"},
    {"unique armour", "Wondertrap", "Silk Slippers"},
    {"unique armour", "Legionstride", "Rough Greaves"},
    {"unique armour", "Trampletoe", "Trimmed Greaves"},
    {"unique armour", "Birth of Fury", "Stone Greaves"},
    {"unique armour", "The Knight-errant", "Mail Sabatons"},
    {"unique armour", "Darkray Vectors", "Braced Sabatons"},
    {"unique armour", "Obern's Bastion", "Stacked Sabatons"},
    {"unique armour", "Northpaw", "Suede Bracers"},
    {"unique armour", "Idle Hands", "Sectioned Bracers"},
    {"unique armour", "Snakebite", "Spined Bracers"},
    {"unique armour", "Candlemaker", "Sombre Gloves"},
    {"unique armour", "Doedre's Tenure", "Stitched Gloves"},
    {"unique armour", "Treefingers", "Riveted Mitts"},
    {"unique armour", "Lochtonial Caress", "Tempered Mitts"},
    {"unique armour", "Radiant Grief", "Lace Hood"},
    {"unique armour", "The Hollow Mask", "Hewn Mask"},
    {"unique armour", "Mask of the Stitched Demon", "Feathered Tiara"},
    {"unique armour", "Atziri's Disdain", "Gold Circlet"},
    {"unique armour", "Ezomyte Peak", "Soldier Greathelm"},
    {"unique armour", "Black Sun Crest", "Wrapped Greathelm"},
    {"unique armour", "Wulfsbane", "Painted Tower Shield"},
    {"unique armour", "Feathered Fortress", "Crescent Targe"},
    {"unique armour", "Crest of Ardura", "Jingling Crest Shield"},
    {"unique armour", "The Lethal Draw", "Sacral Quiver"},
    {"unique armour", "Murkshaft", "Toxic Quiver"},
    {"unique armour", "Drillneck", "Penetrating Quiver"},
    {"unique armour", "Empire's Grasp", "Titan Mitts"},
    {"unique armour", "The Black Insignia", "Corsair Cap"},
    {"unique armour", "Blood Price", "Fierce Greathelm"},
    {"unique armour", "Nocturne", "Wooden Buckler"},
    {"unique armour", "Bloodbarrier", "Iron Buckler"},
    {"unique armour", "Silverthorne", "Spiked Buckler"},
    {"unique armour", "Sacrosanctum", "Corvus Mantle"},
    {"unique armour", "Wanderlust", "Wrapped Sandals"},
    {"unique armour", "Corpsewade", "Iron Greaves"},
    {"unique armour", "The Infinite Pursuit", "Bronze Greaves"},
    {"unique armour", "Wake of Destruction", "Secured Leggings"},
    {"unique armour", "Deathrattle", "Twig Focus"},
    {"unique armour", "Effigy of Cruelty", "Antler Focus"},
    {"unique armour", "Carrion Call", "Engraved Focus"},
    {"unique armour", "The Eternal Spark", "Crystal Focus"},
    {"unique armour", "Apep's Supremacy", "Voodoo Focus"},
    {"unique armour", "Grip of Winter", "Firm Bracers"},
    {"unique armour", "Plaguefinger", "Gauze Wraps"},
    {"unique armour", "Killjoy", "Linen Wraps"},
    {"unique armour", "Shackles of the Wretched", "Aged Cuffs"},
    {"unique armour", "Blueflame Bracers", "Goldcast Cuffs"},
    {"unique armour", "Atsak's Sight", "Veiled Mask"},
    {"unique armour", "The Three Dragons", "Solid Mask"},
    {"unique armour", "The Devouring Diadem", "Wicker Tiara"},
    {"unique armour", "Visage of Ayah", "Beaded Circlet"},
    {"unique armour", "Horns of Bynden", "Rusted Greathelm"},
    {"unique armour", "Wings of Caelyn", "Rusted Greathelm"},
    {"unique armour", "The Smiling Knight", "Cowled Helm"},
    {"unique armour", "The Vile Knight", "Shielded Helm"},
    {"unique armour", "Assailum", "Closed Helm"},
    {"unique armour", "Veil of the Night", "Martyr Crown"},
    {"unique armour", "Keeper of the Arc", "Spiritbone Crown"},
    {"unique armour", "The Surrender", "Stone Tower Shield"},
    {"unique armour", "Oaksworn", "Sigil Crest Shield"},
    {"unique armour", "Saffell's Frame", "Emblem Crest Shield"},
    {"unique armour", "Beyond Reach", "Visceral Quiver"},
    {"unique armour", "Waveshaper", "Tideseer Mantle"},
    {"unique armour", "Valako's Vice", "Plate Gauntlets"},
    {"unique armour", "Dunkelhalt", "Leather Buckler"},
    {"unique armour", "Rondel de Ezo", "Plated Buckler"},
    {"unique armour", "Kaltenhalt", "Ridged Buckler"},
    {"unique armour", "Yriel's Fostering", "Strider Vest"},
    {"unique armour", "The Mutable Star", "Cleric Vestments"},
    {"unique armour", "Powertread", "Hunting Shoes"},
    {"unique armour", "Beetlebite", "Velour Shoes"},
    {"unique armour", "Threaded Light", "Woven Focus"},
    {"unique armour", "Serpent's Lesson", "Tonal Focus"},
    {"unique armour", "Kitoko's Current", "Jewelled Gloves"},
    {"unique armour", "Demon Stitcher", "Intricate Gloves"},
    {"unique armour", "Dreadfist", "Bolstered Mitts"},
    {"unique armour", "Atziri's Acuity", "Moulded Mitts"},
    {"unique armour", "Jarngreipr", "Ringmail Gauntlets"},
    {"unique armour", "Aurseize", "Layered Gauntlets"},
    {"unique armour", "Deathblow", "Doubled Gauntlets"},
    {"unique armour", "Aerisvane's Wings", "Burnished Gauntlets"},
    {"unique armour", "Innsmouth", "Shabby Hood"},
    {"unique armour", "Elevore", "Hunter Hood"},
    {"unique armour", "Mask of the Sanguimancer", "Face Mask"},
    {"unique armour", "Leer Cast", "Hooded Mask"},
    {"unique armour", "Crown of Thorns", "Twig Circlet"},
    {"unique armour", "Deidbell", "Elite Greathelm"},
    {"unique armour", "Corona of the Red Sun", "Warrior Greathelm"},
    {"unique armour", "Erian's Cobble", "Guarded Helm"},
    {"unique armour", "Ironride", "Visored Helm"},
    {"unique armour", "Bronzebeard", "Horned Crown"},
    {"unique armour", "Crown of the Pale King", "Cultist Crown"},
    {"unique armour", "Dionadair", "Splintered Tower Shield"},
    {"unique armour", "Doomgate", "Braced Tower Shield"},
    {"unique armour", "Window to Paradise", "Barricade Tower Shield"},
    {"unique armour", "Lycosidae", "Rampart Tower Shield"},
    {"unique armour", "Arvil's Wheel", "Hardwood Targe"},
    {"unique armour", "Alkem Eira", "Blazon Crest Shield"},
    {"unique armour", "Rise of the Phoenix", "Omen Crest Shield"},
    {"unique armour", "Blackgleam", "Fire Quiver"},
    {"unique armour", "Rearguard", "Blunt Quiver"},
    {"unique armour", "Gloamgown", "Elementalist Robe"},
    {"unique armour", "Nightscale", "Pauascale Gloves"},
    {"unique armour", "Scold's Bridle", "Jade Tiara"},
    {"unique armour", "Calgyra's Arc", "Ornate Buckler"},
    {"unique armour", "Vis Mortis", "Plated Raiment"},
    {"unique armour", "Starkonja's Head", "Leatherbound Hood"},
    {"unique armour", "Heatshiver", "Velvet Cap"},
    {"unique armour", "The Prisoner's Manacles", "Verisium Cuffs"},
    {"unique armour", "Shankgonne", "Covered Sabatons"},
    {"unique armour", "Lightning Coil", "Ancestral Mail"},
    {"unique armour", "Cospri's Will", "Assassin Garb"},
    {"unique armour", "The Auspex", "Exquisite Vest"},
    {"unique armour", "Geofri's Sanctuary", "Revered Vestments"},
    {"unique armour", "The Unleashed", "Revered Vestments"},
    {"unique armour", "Vestige of Darkness", "Tenebrous Crown"},
    {"unique armour", "Decree of Loyalty", "Ancient Mail"},
    {"unique armour", "Decree of Acuity", "Ancient Visor"},
    {"unique armour", "Eyes of the Runefather", "Venerable Defender"},
    {"unique accessory", "The Gnashing Sash", "Wide Belt"},
    {"unique accessory", "Mageblood", "Utility Belt"},
    {"unique accessory", "Headhunter", "Heavy Belt"},
    {"unique accessory", "Bursting Decay", "Unset Ring"},
    {"unique accessory", "Eshtera's Path", "Ring"},
    {"unique accessory", "Safrin's Resolve", "Ring"},
    {"unique accessory", "The Taming", "Prismatic Ring"},
    {"unique accessory", "Kalandra's Touch", "Ring"},
    {"unique accessory", "Zaida's Longevity", "Ring"},
    {"unique accessory", "Dream Fragments", "Sapphire Ring"},
    {"unique accessory", "Choir of the Storm", "Jade Amulet"},
    {"unique accessory", "Berek's Grip", "Two-Stone Ring"},
    {"unique accessory", "Berek's Pass", "Two-Stone Ring"},
    {"unique accessory", "Berek's Respite", "Two-Stone Ring"},
    {"unique accessory", "Astramentis", "Stellar Amulet"},
    {"unique accessory", "Immaculate Adherence", "Solar Amulet"},
    {"unique accessory", "Original Sin", "Amethyst Ring"},
    {"unique accessory", "Yoke of Suffering", "Bloodstone Amulet"},
    {"unique accessory", "Defiance of Destiny", "Jade Amulet"},
    {"unique accessory", "Eventide Petals", "Veridical Chain"},
    {"unique accessory", "Snakepit", "Pearl Ring"},
    {"unique accessory", "Blackflame", "Amethyst Ring"},
    {"unique accessory", "Shavronne's Satchel", "Fine Belt"},
    {"unique accessory", "Call of the Brotherhood", "Topaz Ring"},
    {"unique accessory", "Thief's Torment", "Emerald Ring"},
    {"unique accessory", "Strugglescream", "Stellar Amulet"},
    {"unique accessory", "Ryslatha's Coil", "Ornate Belt"},
    {"unique accessory", "Levinstone", "Topaz Ring"},
    {"unique accessory", "Death Rush", "Emerald Ring"},
    {"unique accessory", "Serpent's Egg", "Gold Amulet"},
    {"unique accessory", "Carnage Heart", "Amber Amulet"},
    {"unique accessory", "Blackheart", "Iron Ring"},
    {"unique accessory", "Doedre's Damning", "Lazuli Ring"},
    {"unique accessory", "Veilpiercer", "Amethyst Ring"},
    {"unique accessory", "Idol of Uldurn", "Crimson Amulet"},
    {"unique accessory", "Igniferis", "Crimson Amulet"},
    {"unique accessory", "Eye of Chayula", "Gold Amulet"},
    {"unique accessory", "The Everlasting Gaze", "Azure Amulet"},
    {"unique accessory", "Ungil's Harmony", "Azure Amulet"},
    {"unique accessory", "Revered Resin", "Amber Amulet"},
    {"unique accessory", "Xoph's Blood", "Amber Amulet"},
    {"unique accessory", "Surefooted Sigil", "Jade Amulet"},
    {"unique accessory", "Ligurium Talisman", "Lapis Amulet"},
    {"unique accessory", "The Pandemonius", "Lapis Amulet"},
    {"unique accessory", "Stone of Lazhwar", "Lapis Amulet"},
    {"unique accessory", "Rondel of Fragility", "Lunar Amulet"},
    {"unique accessory", "The Anvil", "Bloodstone Amulet"},
    {"unique accessory", "Fixation of Yix", "Stellar Amulet"},
    {"unique accessory", "Hinekora's Sight", "Stellar Amulet"},
    {"unique accessory", "Beacon of Azis", "Solar Amulet"},
    {"unique accessory", "Fireflower", "Solar Amulet"},
    {"unique accessory", "Meginord's Girdle", "Rawhide Belt"},
    {"unique accessory", "Midnight Braid", "Rawhide Belt"},
    {"unique accessory", "Ingenuity", "Utility Belt"},
    {"unique accessory", "Cat O' Nine Tails", "Utility Belt"},
    {"unique accessory", "Darkness Enthroned", "Fine Belt"},
    {"unique accessory", "Keelhaul", "Linen Belt"},
    {"unique accessory", "Umbilicus Immortalis", "Linen Belt"},
    {"unique accessory", "Birthright Buckle", "Wide Belt"},
    {"unique accessory", "Byrnabas", "Wide Belt"},
    {"unique accessory", "Soul Tether", "Long Belt"},
    {"unique accessory", "Goregirdle", "Plate Belt"},
    {"unique accessory", "Coward's Legacy", "Mail Belt"},
    {"unique accessory", "Bijouborne", "Double Belt"},
    {"unique accessory", "Zerphi's Genesis", "Heavy Belt"},
    {"unique accessory", "Waistgate", "Heavy Belt"},
    {"unique accessory", "Icefang Orbit", "Iron Ring"},
    {"unique accessory", "Venopuncture", "Iron Ring"},
    {"unique accessory", "Prized Pain", "Iron Ring"},
    {"unique accessory", "Andvarius", "Gold Ring"},
    {"unique accessory", "Perandus Seal", "Gold Ring"},
    {"unique accessory", "Ventor's Gamble", "Gold Ring"},
    {"unique accessory", "Glowswarm", "Lazuli Ring"},
    {"unique accessory", "Seed of Cataclysm", "Lazuli Ring"},
    {"unique accessory", "Blistering Bond", "Ruby Ring"},
    {"unique accessory", "Cracklecreep", "Ruby Ring"},
    {"unique accessory", "Polcirkeln", "Sapphire Ring"},
    {"unique accessory", "Whisper of the Brotherhood", "Sapphire Ring"},
    {"unique accessory", "The Burrower", "Topaz Ring"},
    {"unique accessory", "Ming's Heart", "Amethyst Ring"},
    {"unique accessory", "Vigilant View", "Emerald Ring"},
    {"unique accessory", "Heartbound Loop", "Pearl Ring"},
    {"unique accessory", "Evergrasping Ring", "Pearl Ring"},
    {"unique accessory", "Gifts from Above", "Prismatic Ring"},
    {"unique accessory", "Grip of Kulemak", "Abyssal Signet"},
    {"unique jewel", "Voices", "Sapphire"},
    {"unique jewel", "The Adorned", "Diamond"},
    {"unique jewel", "Controlled Metamorphosis", "Diamond"},
    {"unique jewel", "Against the Darkness", "Time-Lost Diamond"},
    {"unique jewel", "Undying Hate", "Timeless Jewel"},
    {"unique jewel", "Grand Spectrum", "Ruby"},
    {"unique jewel", "Heroic Tragedy", "Timeless Jewel"},
    {"unique jewel", "Flesh Crucible", "Diamond"},
    {"unique jewel", "From Nothing", "Diamond"},
    {"unique jewel", "Split Personality", "Ruby"},
    {"unique jewel", "Megalomaniac", "Diamond"},
    {"unique jewel", "Prism of Belief", "Diamond"},
    {"unique jewel", "Heart of the Well", "Diamond"},
    {"unique flask", "Rite of Passage", "Golden Charm"},
    {"unique flask", "Olroth's Resolve", "Ultimate Life Flask"},
    {"unique flask", "The Fall of the Axe", "Silver Charm"},
    {"unique flask", "For Utopia", "Stone Charm"},
    {"unique flask", "Nascent Hope", "Thawing Charm"},
    {"unique flask", "Lavianga's Spirits", "Gargantuan Mana Flask"},
    {"unique flask", "Uhtred's Chalice", "Transcendent Mana Flask"},
    {"unique flask", "Beira's Anguish", "Dousing Charm"},
    {"unique flask", "Opportunity", "Ultimate Life Flask"},
    {"unique flask", "Melting Maelstrom", "Ultimate Mana Flask"},
    {"unique flask", "Blood of the Warrior", "Gargantuan Life Flask"},
    {"unique flask", "Valako's Roar", "Topaz Charm"},
    {"unique flask", "Sanguis Heroum", "Staunching Charm"},
    {"unique flask", "The Black Cat", "Grounding Charm"},
    {"unique flask", "Ngamahu's Chosen", "Ruby Charm"},
    {"unique flask", "Forsaken Bangle", "Amethyst Charm"},
    {"unique flask", "Arakaali's Gift", "Antidote Charm"},
    {"unique flask", "Breath of the Mountains", "Sapphire Charm"},
    {"unique sanctum", "The Last Flame", "Incense Relic"},
    {"unique sanctum", "The Desperate Alliance", "Vase Relic"},
    {"unique sanctum", "The Changing Seasons", "Seal Relic"},
    {"unique sanctum", "The Burden of Leadership", "Tapestry Relic"},
    {"unique sanctum", "The Peacemaker's Draught", "Amphora Relic"},
};

inline constexpr size_t kUniqueCatalogCount = sizeof(kUniqueCatalog) / sizeof(kUniqueCatalog[0]);

}
